Improv language support
Amulet-Team/Amulet-Map-Editor pull request #268
Opened 2021-04-18 21:28 UTC by ALTB0ne

I improved the language support a bit (43 new entries, 3 modifications).

I basically just added `lang.get()` in some places, and added their corresponding entries in `en.lang`. I kept it simple and didn't change any of the code logic, so this may not be optimal in some places depending on where the original text was. (in `__init__` files for example)

This means you may not want some of the changes made here in favor of a more in-depth code refactoring (before adding the corresponding language support).

_Black has been used for formatting in the last commit.
`test_lang.py` has been run, and changes were tested manually._

### The changes:

- Moved some colons characters inside their lang entries for better customization (those are the 3 modifications, and the only case were I modified other lang files)
- Added some missing localization here and there (Discord button, some dialogue titles, ...)
- Localized some message boxes
- Localized update checker
- Added missing calls for tab names (lang entries did already exist)
- Localized the menu bar
- Localized the loading screen of the 3D editor's canvas

2021-04-30 09:44 UTC, gentlegiantJGC commented on amulet_map_editor/api/framework/amulet_ui.py
> +        menu_dict.setdefault(f"&{lang.get('menu_bar.file.menu_name')}", {}).setdefault(
The "&" symbol should be part of the localised string.
This is a special character in this context that is used as a shortcut when the alt key is pressed.
"&File" translates to "File" in the menu and when you press atl+f it will open the file menu.
Leaving this as the hard coded first character may lead to multiple menus attached to the same key codes.

More info can be found here
https://docs.wxpython.org/wx.MenuItem.html#wx.MenuItem.SetItemLabel

2021-04-30 09:48 UTC, gentlegiantJGC commented on amulet_map_editor/api/framework/pages/world_page.py
> +]
I think we need to find a better way to localise program names to avoid conflicts

2021-04-30 09:56 UTC, gentlegiantJGC commented on amulet_map_editor/programs/edit/edit.py
> +                f"{lang.get('menu_bar.edit.redo')}\tCtrl+y": lambda evt: self._canvas.redo(),
These should be `program_3d_edit.menu_bar._____` because they are specific to the 3d editor

2021-04-30 10:23 UTC, gentlegiantJGC requested changes
This looks pretty good so far.
The only changes that need making are
- the "&" symbol in all the menubars should be part of the localised string
- menubar keys should have `program_3d_edit.` prepended

I will look into the program naming strings.

Just so you are aware we do not currently have a licence applied to this project so any code contributions you make are made with the agreement that the code can be distributed under whatever licence we eventually choose.

2021-05-03 00:40 UTC, ALTB0ne commented
Changes done:

- Move `&` inside translations;
- Prepend menubar keys with `program_3d_edit.`:
  - Except `menu_bar.options.menu_name` & `menu_bar.help.menu_name`, since they're menu _names_ which _could (?)_ be used by other subprograms (other keys in _options_ & _help_ menu tabs have been prepended, because they are specific to the 3d editor);
- Merge Chinese translations pull request (thanks yudonglin);
- Add French translations.

I didn't touch the part in `amulet_map_editor/api/framework/pages/world_page.py` ln 18-20.

I'm aware for the licence thing, no problem.

_Black has been used for formatting again. `test_lang.py` is fine too._

2021-05-09 10:37 UTC, gentlegiantJGC commented on amulet_map_editor/api/framework/pages/world_page.py
> +]
Looking at this again program names do not need to be unique so this is fine.
I was also going to look into storing the name with the class but this is fine.

2021-05-09 11:00 UTC, gentlegiantJGC approved these changes

2021-05-09 11:07 UTC, merged