Improved logging
Amulet-Team/Amulet-Map-Editor pull request #647
Opened 2022-04-20 10:33 UTC by gentlegiantJGC

Switched to getLogger to get the logger instead of importing the object.
Added file handlers for the libraries.
Merged the file output into one file.
Made the file include the process id so that each process has its own log file.

This is dependent upon the following library pull requests.
https://github.com/Amulet-Team/Amulet-Core/pull/183
https://github.com/gentlegiantJGC/Minecraft-Model-Reader/pull/12
https://github.com/gentlegiantJGC/PyMCTranslate/pull/16

Please review and I will merge when ready.

2022-05-10 03:47 UTC, Podshot requested changes

2022-05-10 03:47 UTC, Podshot commented on amulet_map_editor/programs/edit/edit.py
> +EDIT_CONFIG_ID = "amulet_edit"
This seems to already be defined earlier in the file, are one of these definitions supposed to be removed or is this intentional?

2022-05-10 08:53 UTC, gentlegiantJGC commented on amulet_map_editor/programs/edit/edit.py
> +EDIT_CONFIG_ID = "amulet_edit"
looks like an error when I was merging the branches

2022-05-10 09:04 UTC, gentlegiantJGC commented on amulet_map_editor/programs/edit/edit.py
> +EDIT_CONFIG_ID = "amulet_edit"
Just fixed this. Thanks for pointing it out

2022-05-11 08:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Amulet-Team/Amulet-Map-Editor?pullRequest=647) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Amulet-Team/Amulet-Map-Editor?pullRequest=647) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Amulet-Team/Amulet-Map-Editor?pullRequest=647) it.</sub>

2022-05-17 05:23 UTC, Podshot approved these changes
Looks all good to me in it's current state! If any changes need to be made before it's merged I can do a quick review of them

2022-07-29 10:14 UTC, merged