improv-lang-zh_CN
Amulet-Team/Amulet-Map-Editor pull request #836
Opened 2022-11-23 23:34 UTC by 1834423612

> Add and Change zh-CN translations

Hi, 
I have made some modifications to the translation of zh_CN according to the operation interface and usage functions and added a few places that have not been translated.

Since the translation from the original language (English) to Chinese may have some doubts for users, I explained the Amulet interface according to the method that Chinese users can easily understand waht does it means. 
And I added the explanation in parentheses after the translated content.

This is my first time to Pull requests, something maybe was not very well.😊 
Thank you.

2022-11-26 09:36 UTC, gentlegiantJGC approved these changes
Thanks. This looks good

2022-11-26 09:41 UTC, gentlegiantJGC requested changes

2022-11-26 09:41 UTC, gentlegiantJGC commented on amulet_map_editor/lang/zh_CN.lang
>  program_3d_edit.canvas.downloading_bedrock_vanilla_resource_pack=正在下载基岩版纯净资源包
These two lines are duplicated. Please delete one of them.

2022-11-26 16:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Amulet-Team/Amulet-Map-Editor?pullRequest=836) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Amulet-Team/Amulet-Map-Editor?pullRequest=836) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Amulet-Team/Amulet-Map-Editor?pullRequest=836) it.</sub>

2022-11-26 16:56 UTC, 1834423612 commented on amulet_map_editor/lang/zh_CN.lang
>  program_3d_edit.canvas.downloading_bedrock_vanilla_resource_pack=正在下载基岩版纯净资源包
Sorry, I forget it, now is changed😃

2022-11-27 16:10 UTC, gentlegiantJGC approved these changes

2022-11-27 16:11 UTC, merged